#include <Render/OpenGL/OpenGL.h>

// Color mapping
int COLOR_RGB = GL_RGB;
int COLOR_RGBA = GL_RGBA;
int COLOR_RGB16F = GL_RGB16F;
int COLOR_RED = GL_RED;
int COLOR_RED16F = GL_R16F;
int COLOR_RED32F = GL_R32F;
int COLOR_DEPTH_COMPONENT32F = GL_DEPTH_COMPONENT32F;
int COLOR_DEPTH_COMPONENT24 = GL_DEPTH_COMPONENT24;
int COLOR_DEPTH_COMPONENT = GL_DEPTH_COMPONENT;

int TEXTURE_TYPE_BYTE = GL_UNSIGNED_BYTE;
int TEXTURE_TYPE_FLOAT = GL_FLOAT;

int TEST_EQUAL = GL_EQUAL;
int TEST_LEQUAL = GL_LEQUAL;
int TEST_GEQUAL = GL_GEQUAL;
int TEST_LESS = GL_LESS;
int TEST_GREATER = GL_GREATER;
int TEST_ALWAYS = GL_ALWAYS;

int FILTER_NEAREST = GL_NEAREST;
int FILTER_LINEAR = GL_LINEAR;
int FILTER_MIPMAP = GL_LINEAR_MIPMAP_LINEAR;

int COLOR_BUFFER_BIT = GL_COLOR_BUFFER_BIT;
int DEPTH_BUFFER_BIT = GL_DEPTH_BUFFER_BIT;
int STENCIL_BUFFER_BIT = GL_STENCIL_BUFFER_BIT;

int DRAW_TRIANGLES = GL_TRIANGLES;
int DRAW_TRIANGLE_STRIP = GL_TRIANGLE_STRIP;

int DRAW_BUFFER_NONE = GL_NONE;
int DRAW_BUFFER_FRONT = GL_FRONT;
int DRAW_BUFFER_BACK = GL_BACK;

int BLEND_ZERO = GL_ZERO;
int BLEND_ONE = GL_ONE;
int BLEND_SRC_COLOR = GL_SRC_COLOR;
int BLEND_ONE_MINUS_SRC_COLOR = GL_ONE_MINUS_SRC_COLOR;
int BLEND_SRC_ALPHA = GL_SRC_ALPHA;
int BLEND_ONE_MINUS_SRC_ALPHA = GL_ONE_MINUS_SRC_ALPHA;
int BLEND_DST_ALPHA = GL_DST_ALPHA;
int BLEND_ONE_MINUS_DST_ALPHA = GL_ONE_MINUS_DST_ALPHA;

int TEXTURE_REPEAT_X = GL_TEXTURE_WRAP_S;
int TEXTURE_REPEAT_Y = GL_TEXTURE_WRAP_T;

int TEXTURE_REPEAT_MODE_REPEAT = GL_REPEAT;
int TEXTURE_REPEAT_MODE_CLAMP = GL_CLAMP_TO_BORDER;

int CUBEMAP_FACE_RIGHT = GL_TEXTURE_CUBE_MAP_POSITIVE_X;
int CUBEMAP_FACE_LEFT = GL_TEXTURE_CUBE_MAP_NEGATIVE_X;
int CUBEMAP_FACE_TOP = GL_TEXTURE_CUBE_MAP_POSITIVE_Y;
int CUBEMAP_FACE_BOTTOM = GL_TEXTURE_CUBE_MAP_NEGATIVE_Y;
int CUBEMAP_FACE_BACK = GL_TEXTURE_CUBE_MAP_POSITIVE_Z;
int CUBEMAP_FACE_FRONT = GL_TEXTURE_CUBE_MAP_NEGATIVE_Z;

int CULLMODE_FRONT = GL_FRONT;
int CULLMODE_BACK = GL_BACK;
